services:

  xero-mock-server:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"

  show-me-the-money-backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - XERO_SERVICE_URL=http://host.docker.internal:3000
    volumes:
      - type: bind
        source: ./backend/src
        target: /backend/src

  show-me-the-money-webapp:
    build: ./webapp
    ports:
      - "3002:3002"
    depends_on:
      - show-me-the-money-backend
    environment:
      - PORT=3002
      - BACKEND_URL=http://host.docker.internal:3001
    volumes:
      - type: bind
        source: ./webapp/src
        target: /webapp/src

